/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'docu-tutorials'}],
  hardwareSidebar: [{type: 'autogenerated', dirName: 'hardware'}],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  // px4Sidebar: [{type: 'autogenerated', dirName: 'software/px4'}],
  // betaflightSidebar: [{type: 'autogenerated', dirName: 'software/betaflight'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

// const sidebars = {
//   mySidebar:[
//     // 'intro',
//     {
//       type: 'category',
//       label: 'Hardware',
//       items: [
//         'frame',
//         {
//           type: 'autogenerated',
//           dirName: 'hardware/frame', // Generate sidebar slice from docs/hardware/frame
//         },
//         'propulsion',
//         {
//           type: 'autogenerated',
//           dirName: 'hardware/propulsion', // Generate sidebar slice from docs/hardware/propulsion
//         },
//         // 'tutorial-end',
//       ],
//     },
//     {
//       type: 'autogenerated',
//       dirName: '.', // Generate sidebar slice from docs
//     },
//     {
//       type: 'category',
//       label: 'Software',
//       items: [
//         'Betaflight',
//         {
//           type: 'autogenerated',
//           dirName: 'software/betaflight'
//         }, 
//         'PX4',
//         {
//           type: 'autogenerated',
//           dirName: 'software/px4'
//         },
//       ],
//     },
//   ],
// };

module.exports = sidebars;
// module.exports = {
//   themeConfig: {
//     docs: {
//       sidebar: {
//         hideable: true,
//       },
//     },
//   },

//   tutorialSidebar:[{type: 'autogenerated', dirName: '.'}],

//   hardwareSidebar: [{type: 'autogenerated', dirName: 'hardware'}],

//   sidebars
// };